// Generated by CoffeeScript 1.3.3
(function() {

  (typeof exports !== "undefined" && exports !== null ? exports : window).Formations = {
    eyes: " 4\no o",
    triangle: " 4\n-o\no o",
    easy: " 6\nooo",
    clover: " 10\nx o\n-o\no x",
    tetris: " 8\no\nx\no\no",
    delta: " 12\n--o\n-x x\no   o",
    tank: " 14\n-o\nx x\no o\n-x",
    block: " 12\noxx\nxox\nxxo",
    fortress: " 20\noxxxx\nx   x\nx o x\nx   x\nxxxxo",
    snake: " 16\n--o\n-x\n--o\n-x\no",
    lobster: " 16\no o\nx x\n-o\n-x\n-x",
    hat: " 14\n-oxo\n-x x\nxxoxx",
    arrow: " 20\n--o\n-xxx\noxxxo\n-xxx\n-xxx",
    table: " 16\nxxoxx\n-o o",
    patchwork: " 20\n-x x\no x o\n-x x\nx o x\n-x x",
    volcano: " 16\n--o\n-xxx\noxxxo",
    spiral: " 22\n-xx\nx o x\nx   x\n-oxo",
    glider: " 13\n-o\n--o\nxox",
    giraffe: " 15\nox\n-x\n-x\n-x\n-x\n-x    o\n-oxxxx\n-x   x\n-x   x",
    wave: " 20\n-xxx\no   x   o\n-----xxx\n-xxx\nx   x   o\n-----xxx"
  };

}).call(this);
