version: '3'

services:
  swarmation:
    image: steadicat/swarmation
    container_name: swarmation
    build:
      context: .
      dockerfile: Dockerfile
      target: node
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - SECRET
      - AIRTABLE_KEY
      - AIRTABLE_BASE
      - POSTMARK
